jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  cache:
    type: simple
    cache-names: userSearch

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true

cloud:
  aws:
    region:
      static: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket-name: ${S3_BUCKET_NAME:spring-plus-profile-images}
    stack:
      auto: false

logging:
  level:
    org.springframework.security: ${LOG_LEVEL:DEBUG}
    org.example.expert: ${LOG_LEVEL:DEBUG}
    com.amazonaws: WARN